---
# Source: microservice/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: microservice
  labels:
    helm.sh/chart: microservice-0.1.0
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: microservice
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: microservice
    app.kubernetes.io/instance: microservice
